#### Задание на повторение материала

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [12]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [13]:
a1 = a.reshape(4,3)
print(a1)
a2 = a.reshape(3,4)
print(a2)
a3 = a.reshape(2,6)
print(a3)
a4 = a.reshape(6,2)
print(a4)
a5 = a.reshape(4,3,order='F')
print(a5)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 16 20]
 [13 17 21]
 [14 18 22]
 [15 19 23]]


Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [14]:
a1 = a.reshape(4,-1)
print(a1)
a2 = a.reshape(-1,4)
print(a2)
a3 = a.reshape(-4,6)
print(a3)
a4 = a.reshape(6,-4)
print(a4)
a5 = a.reshape(4,-1,order='F')
print(a5)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12 16 20]
 [13 17 21]
 [14 18 22]
 [15 19 23]]


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

да

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [38]:
rand_z=np.random.normal(size=12).reshape(3,-1)
rand_z.size

12

In [23]:
rand_z_flat=rand_z.flatten()
rand_z_flat.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [27]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2.


In [28]:
b = np.arange(20,1,-2).reshape(10,-1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

 В чем разница между массивами a и b?

In [33]:
# в форме
print(a.shape, b.shape)

(10,) (10, 1)


Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [63]:
a = np.zeros((2,2))
b = np.ones((3,2))
c = np.vstack((a, b))
print(c, c.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 10


Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [81]:
a = np.arange(12)
print(a)
A = a.reshape(4,-1)
print(A)
At = A.T
print(At)
B = np.dot(A,At)
print(B)
print(B.size)
# print(np.linalg.inv(B))
# LinAlgError: Singular matrix

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
16


Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [82]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [89]:
c=np.random.randint(0,16,16)
print(c)

[13  6 11  8 13  7  4 15 12  1 14  4  7  9  8 11]


Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [100]:
C=c.reshape(4,-1)
D=C*10+B
print(D)
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv=np.linalg.inv(D)
print(D_inv)

[[135  74 133 112]
 [144 120 126 272]
 [143  96 289 252]
 [102 212 292 412]]
-311614800.00000006
4
[[ 5.88624160e-03  4.77628149e-03  3.00370842e-05 -4.77178876e-03]
 [ 1.83065759e-02 -9.94265998e-03 -1.49057105e-02  1.07046264e-02]
 [ 1.28517644e-03 -6.51997274e-03  4.49015900e-03  1.20867173e-03]
 [-1.17880152e-02  8.55460010e-03  4.48014664e-03 -2.75628757e-03]]


Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [124]:
_D_inv=D_inv.copy()
_D_inv[_D_inv>0]=1
_D_inv[_D_inv<0]=0
print(_D_inv)
# ?np.where
print(B)
print(C)
E=np.where(_D_inv, B, C)
print(E)

[[1. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 1. 1.]
 [0. 1. 1. 0.]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[13  6 11  8]
 [13  7  4 15]
 [12  1 14  4]
 [ 7  9  8 11]]
[[  5  14  23   8]
 [ 14   7   4 122]
 [ 23   1 149 212]
 [  7 122 212  11]]
